//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
let peePee = () => {
    let sum = 0;
    let poopoo = peepee();

    for (let i = 0, n = peepee.length; i < n; i++) {
        sum += poopoo[i];
    }

    console.log(sum);
}

let peepee = () => {
    let a = 1;
    let b = 2;
    let c = a + b;
    var poopoo = [];
    while(c < 4000000){
        if (c % 2 === 0) {
            poopoo.push(c);
        }
        a = b;
        b = c;
        c = a + b;
    }
    return poopoo;
}