//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

let peepee = (lim) => {

    let sum = 0

    let a = 1;
    let b = 2;
    if ( lim >= 2 ){
       sum = sum + b 
    }
    let c 
    while(c <= lim){
        c = a + b
        if( c %2 == 0){
            sum = sum + c
        }
    }

    return sum;
}

console.log("The answer is " + peepee(10));